# Site settings
title: D Lab
description: DLab@AMC / 서울아산병원 디지털의학 연구실

url: "https://ydon1111.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: ""


lang: "ko_KR"
timezone: "Asia/Seoul"
future: true

# Build settings
markdown: kramdown

