# Site settings
title: D Lab
description: 
  "서울아산병원 디지털헬스케어 연구실"
url: "https://ydon1111.github.io" 
baseurl: "https://ydon1111.github.io" 
masthead_title: "서울아산병원 디지털 헬스케어 연구실" 

lang: ko
timezone: Asia/Seoul

# Build settings
markdown: kramdown

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false   # 읽는데 걸리는 소요시간 표시
      show_date: true    # 포스팅 날짜 표시
      comments: true
      share: true
      related: true