# Site settings
title: D Lab
description: DHLab@AMC / 서울아산병원 디지털헬스케어 연구실

url: "https://ydon1111.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: ""

lang: ko
timezone: Asia/Seoul
future: true

# Build settings
markdown: kramdown

