# Site settings
title: D Lab
subtitle: DHLab@AMC
description: "서울아산병원 디지털헬스케어 연구실"


url: "https://ydon1111.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io


masthead_title: "서울아산병원 디지털 헬스케어 연구실"

lang: ko
timezone: Asia/Seoul
future: true

# Build settings
markdown: kramdown

# Defaults 설정
defaults:
  - scope:
      path: ""
      type: "home"
    values:
      layout: "default"
      author_profile: true
      title: D Lab
      description: "서울아산병원 디지털헬스케어 연구실"